### ISSUE TITLE
[GCD] Understanding Magneticum

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#10]
> estimate 6
> remaining 2020-09-11 5
- [ ] 1 General understanding of what Magneticum provides
- [ ] Understand structure of the data that Magneticum provides

**Comment by Joshuaalbert** [comment]
merge with #20

**Comment by MGJvanGroeningen** [comment]
Closing this issue since it's inherent to #20
