### ISSUE TITLE
[GCD] Understanding state-of-art methods of ICM reconstruction

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#11]
estimate 6
remaining 2020-09-10 6
remaining 2020-11-10 2
- [ ] Understand state-of-art methods of ICM reconstruction: look up related work from M. Bruggen from Hamburg using ADS.
- [x] Understand added value of own research: knowing what problem you will solve.
- [X] Be able to describe what immediate benefits would come from your work if it is successful.

**Comment by Joshuaalbert** [comment]
https://arxiv.org/pdf/1810.07703.pdf
https://arxiv.org/abs/1810.08430v1

**Comment by Joshuaalbert** [comment]
Undone, but time to move on
