### ISSUE TITLE
[SCD] Determining the telescope

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#12]
> estimate 3
> remaining 2020-11-20 2

- [x] What observables are we interested in
- [ ] What telescopes can provide these observables
- [ ] What telescope can we simulate
- [ ] What are the initial conditions for star cluster simulations, how do these map to AMUSE IC functions?
- [ ] What is their link to physical initial conditions

**Comment by Joshuaalbert** [comment]
unneedde
