### ISSUE TITLE
[SCD] Learn how AMUSE works

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#13]
> estimate 6
> remaining 2020-10-30 5
> remaining 2020-11-20 3

- [x] Setup AMUSE environment/Run simple simulation
- [x] Run star cluster simulation: gas free
- [ ] Run star cluster simulation: with gas (Martijn)
- [x] Be able to save the results in snapshots throughout the simulation time.
- [ ] How can stars be represented in simulations
- [ ] How is their evolution implemented
- [ ] How is their formation implemented
- [ ] How are stellar dynamics implemented
- [ ] How are gas dynamics implemented
- [ ] How is feedback implemented

**Comment by Joshuaalbert** [comment]
Don't need amuse
