### ISSUE TITLE
[SCD] Simulate Telescope Observables

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#17]
> estimate 6
> remaining 2020-10-19 5
> remaining 2020-10-19 4

- [x] What are the Gaia observables?
- [ ] What information is given in Gaia observables and how is it formatted
- [ ] How can you extract them form a simulation in AMUSE (Anthony Brown?)
- [ ] Simulate Gaia observables

**Comment by Joshuaalbert** [comment]
https://pypi.org/project/PyGaia/

https://www.cosmos.esa.int/web/gaia/science-performance

**Comment by JuliusHendrix** [comment]
DR1:
https://www.cosmos.esa.int/web/gaia/dr1

DR2:
https://www.cosmos.esa.int/web/gaia/dr2

**Comment by JuliusHendrix** [comment]
AMUSE star cluster simulation example with galaxia:
https://github.com/amusecode/amuse/blob/master/examples/examples_galaxia/evolution_cluster.py

**Comment by Joshuaalbert** [comment]
done
