### ISSUE TITLE
[SCD] Build data generation pipeline

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#18]
> estimate 4

- [ ] Extra: What inputs does a graph network expect?
- [ ] Format the Gaia data to be suitable for the graph network
- [ ] Visualize the input data

**Comment by Joshuaalbert** [comment]
https://github.com/tensorflow/datasets/blob/311280c12f8b4aa9e5634f60cd8a898c3926c8e5/tensorflow_datasets/core/dataset_builder.py#L1009

example: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/question_answering/web_questions.py

**Comment by Joshuaalbert** [comment]
Reading:

https://arxiv.org/pdf/2003.09011.pdf

https://ui.adsabs.harvard.edu/abs/2003ARA%26A..41...57L/abstract

https://ui.adsabs.harvard.edu/abs/2020arXiv201106105C/abstract

https://ui.adsabs.harvard.edu/abs/2013ApJ...777..173B/abstract

https://arxiv.org/pdf/2011.10788.pdf

**Comment by Joshuaalbert** [comment]
done
