### ISSUE TITLE
[SCD] Understand data visualisation

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#19]
> estimate 4
> remaining 2020-11-11 3
> remaining 2020-11-20 1

- [x] What are different ways to visualize data?
- [ ] What is the best data visualization for Gaia observables?
- [x] What is the best data visualization for the ISM?

- [x] Explore Mayavi and yt

**Comment by JuliusHendrix** [comment]
pynbody & pysph seem to be helpful for sph particle visualization.

**Comment by Joshuaalbert** [comment]
done, after you use mayavi to visualise your clusters to make sure you seen the structure in the center
