### ISSUE TITLE
[SCD] Understand star cluster science

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/neural_deprojection#2]
> estimate 10
> remaining 2020-09-07 10
> remaining 2020-09-13 8
> remaining 2020-09-14 6
> remaining 2020-09-16 5
> remaining 2020-09-17 4
> remaining 2020-09-20 2
> remaining 2020-09-24 0
- [x] Dynamics

- [x] Content

- [x] Life cycle

**Comment by Joshuaalbert** [comment]
@JuliusHendrix Please read https://ui.adsabs.harvard.edu/abs/2014PhR...539...49K/abstract
Follow the methodology in https://github.com/Joshuaalbert/neural_deprojection/issues/1#issuecomment-689466653  and skim quickly first, read deeper and follow appropriate links secondly. Don't forget to be saving appropriate articles to your ads library.

**Comment by JuliusHendrix** [comment]
Found a recent review that will contain most of the information (if not all) for this topic:
[link](https://ui.adsabs.harvard.edu/abs/2019ARA%26A..57..227K/abstract)
I'm adjusting my time estimate to account for this other paper.
