### ISSUE TITLE
[GCD] How do the snapshots of the Magneticum simulation convert to physical quantities?

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#20]
> estimate 7
> remaining 2020-10-10 7
> remaining 2020-10-19 5
> remaining 2020-11-10 2

- [x] Understand Magneticum snapshot data format
- [x] Understand physical conversion from magneticum simulation snapshot to physical quantities
- [x] Create/understand code that can convert snapshots to physical quantities
- [x] Decide a data format that SOXS understands/understand how to interface with SOXS

**Comment by Joshuaalbert** [comment]
Use https://gitlab.lrz.de/di29bop/g3t/blob/master/stable/c2pap_batch.py to pull clusters in batch mode.
You just need to download the cvs table with the selected objects from the web portal (for example from ClusterSelect) and then use something like,

```bash
python c2pap_batch.py -u 'your@email' -x 'password' -f dataset.csv -s SimCut -p r500factor=2 IMG_Z_SIZE=2000 -e -j jobs_cache.pk
```

You can read about `r500factor=2 img_z_size=200` by reading about params of SimCut on the webportal. There's a paper describing magneticum portal, https://ui.adsabs.harvard.edu/abs/2017A%26C....20...52R/abstract

You need to register to use magneticum.

**Comment by Joshuaalbert** [comment]
Here's an example of a cluster I downloaded, plotted with matplotlib and pynbody. Edit: This is only the start content ;) There is also gas and darkmatter, which I didn't plot.
![Screenshot from 2020-10-21 11-42-55](https://user-images.githubusercontent.com/14807032/96703052-b4899300-1392-11eb-8482-eab11e324cfc.png)

**Comment by MGJvanGroeningen** [comment]
Used a pretty big cluster, haven't checked whether gas, dm and stars use the same particles, but this looks pretty nice for a start. I had to adjust the c2pap_batch.py a bit to get it to work (mainly problems where byte types were given and str types were needed (I think) or vice versa).

![simcut_example](https://user-images.githubusercontent.com/35311108/96745793-cdac3700-13c6-11eb-8fa0-bba7bbaca09a.png)

**Comment by Joshuaalbert** [comment]
By the way, Klaus asked that we start with a small number of clusters and then report back that it works. So I'm guessing it works! I'll let him know.

**Comment by Joshuaalbert** [comment]
You have two options mayavi and yt. It looks like yt is more favoured in astronomy for visualisations, so you should use that one unless you encounter a problem. There are many tutorials here: https://yt-project.org/doc/cookbook
