### ISSUE TITLE
[GCD] How does SOXS work?

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#22]
> estimate 6
> remaining 2020-10-10 6
> remaining 2020-10-20 5
> remaining 2020-11-20 3
> remaining 2020-12-2 2

- [x] What is SOXS? What is it used for?
- [x] 1 How does SOXS simulate Chandra images from galaxy clusters? Photon lists.
- [x] 1 How is this coded up?

**Comment by Joshuaalbert** [comment]
https://github.com/jzuhone/pyxsim

**Comment by Joshuaalbert** [comment]
https://github.com/jzuhone/pyxsim/issues/14

**Comment by Joshuaalbert** [comment]
To overcome _png error:

https://stackoverflow.com/questions/3331443/import-matplotlib-png-fails

**Comment by MGJvanGroeningen** [comment]
Fixed it :) found another matplotlib/_png.py on my computer and copied it to the right directory

> To overcome _png error:
> 
> https://stackoverflow.com/questions/3331443/import-matplotlib-png-fails

**Comment by Joshuaalbert** [comment]
great
