### ISSUE TITLE
[GCD] Creating the training data pipeline

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#23]
> estimate 6
> remaining 2020-10-10 6
> remaining 2020-12-2 3

- [x] Make a TF dataset object
- [ ] Create the pipeline

**Comment by Joshuaalbert** [comment]
Fill out _generate_examples of https://github.com/tensorflow/datasets/blob/358b069bbb83ae6f7a0cb7bd65940c0c0addf283/tensorflow_datasets/core/dataset_builder.py#L996

**Comment by Joshuaalbert** [comment]
done
