### ISSUE TITLE
[GCD] Collaboration D: Learn how to visualize 3D volumes with Mayavi

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#24]
> estimate 6
> remaining 2020-10-10 6
> remaining 2020-10-28 4
> remaining 2020-11-10 2

- [x] Mayavi general understanding. What is it? How does it work?
- [x] 1 Create visualization of galaxy clusters simulations and their projections

**Comment by Joshuaalbert** [comment]
Explote yt as well since pyxsim uses it.

**Comment by Joshuaalbert** [comment]
@MGJvanGroeningen I tried to render a snapshot in yt and had a problem. magneticum is a SPH code, and yt was built for mesh codes. In mesh codes you have something like voxels, where as with SPH you have particles and you need to compute the physical fields from them by convolving a proper kernel. Anyways, yt just started supporting SPH codes, but I found an error with it. Maybe you can spend a bit trying their "volume rendering" approach.
