### ISSUE TITLE
[GCD] Graph networks

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#27]
> estimate 12
> remaining 2020-12-9 12

Understand conceptually how graph networks can be used in the project. 
- [ ] How does it fit in a neural network for deprojection, i.e. how can it be used to translate an X-ray image to a 3D probability field for rho, U, etc.? 
- [ ] Why would it be better than other neural network structures? Why would it be worse?

Be able to understand and write graph network code.
- [ ] How to (efficiently) encode the nodes, edges and global variables? 
- [ ] How to update the nodes, edges and global variables? 
- [ ] How to get useful information from the graph network?
- [ ] Is Spektral useful and how can it be implemented?

**Comment by Joshuaalbert** [comment]
Done as of the last meeting
