### ISSUE TITLE
[GCD] Validation of training data

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#28]
> estimate 4
> remaining 2020-12-9 4
> remaining 2020-12-10 2

- [x] Is the X-ray image centered on the simulation?
- [ ] What are the best/correct parameter values for creating the mock X-ray images? (e.g. exposure time, detection area, redshift, photon energy range)

**Comment by Joshuaalbert** [comment]
Past this point
