### ISSUE TITLE
[GCD] Alternative data and methods

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#29]
> estimate 4
> remaining 2020-12-9 4
> remaining 2020-12-19 2

- [x] Check out the BAHAMAS and MACSIS data sets. Try to use yt/pynbody/mayavi to visualize the datasets.
- [ ] Find a reliable function to convert sph particles to grid values for different quantities (rho, U). Try the function pynbody.sph.to_3d_grid() or the package from Julius Donnert.

**Comment by Joshuaalbert** [comment]
Done
