### ISSUE TITLE
[SCD] Vanilla Neural Network Architectures & Training Protocols

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#3]
> estimate 4
> remaining 2020-09-09 4
> remaining 2020-10-30 2

- [x] Common architectures

- [x] Kaggle

- [x] Common training algorithms

**Comment by Joshuaalbert** [comment]
Taking this off the "explain to group milestone", because it's not directly needed to convey the project's concept.

**Comment by Joshuaalbert** [comment]
https://medium.com/apache-mxnet/transposed-convolutions-explained-with-ms-excel-52d13030c7e8

**Comment by Joshuaalbert** [comment]
hyper params for Monet GAN:

activation: https://medium.com/@lessw/meet-mish-new-state-of-the-art-ai-activation-function-the-successor-to-relu-846a6d93471f

kernel size

Resource: https://www.tensorflow.org/hub/tutorials

**Comment by Joshuaalbert** [comment]
https://keras.io/api/callbacks/learning_rate_scheduler/

**Comment by Joshuaalbert** [comment]
https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d

**Comment by Joshuaalbert** [comment]
@MGJvanGroeningen See these links I'm posting here for you too.
