### ISSUE TITLE
GCD offsets and scales

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#31]
These numbers represent the mean of the means and the mean of the standard deviations of relevant features of the clusters. They will be used as offsets and scales to normalize the input for the model.

Snapshot : snap_128
Simulation : Magneticum
Clusters : 188
 
offset x : 196481.40501172983 
scale x : 1170.9940781554744 
offset y : 190155.74350430627 
scale y : 1483.9831650762792 
offset z : 189615.6717511062 
scale z : 449.11233237926893 
offset vx : -6.677304333609914 
scale vx : 376.757255396608 
offset vy : 1.2930944166146907 
scale vy : 381.73884338244255 
offset vz : 1.2656112332971723 
scale vz : 362.0345063415572 
offset rho : -14.522707903518079 (log)
scale rho : 1.6356572110313903 (log)
offset U : 12.734080567920001 (log)
scale U : 1.5353510159769392 (log)
 

Snapshot : snap_132
Simulation : Magneticum
Clusters : 211
 
offset x : 196078.40085125767 
scale x : 1302.67167001332 
offset y : 187784.09984704907 
scale y : 1360.8610368947657 
offset z : 186084.16630058078 
scale z : 439.97802116647523 
offset vx : -2.199339034692706 
scale vx : 372.9998791591907 
offset vy : -7.969863129698386 
scale vy : 376.65391463577464 
offset vz : -2.9193162532938057 
scale vz : 358.5134433491501 
offset rho : -14.4535418137662 (log)
scale rho : 1.6209617154385314 (log)
offset U : 12.765081795243058 (log)
scale U : 1.5722075031995633 (log)
 

Snapshot : snap_136
Simulation : Magneticum
Clusters : 225
 
offset x : 193270.49230113826 
scale x : 1045.2802349735177 
offset y : 184644.11093413163 
scale y : 1262.5216957535029 
offset z : 183268.6645676234 
scale z : 431.9230865541955 
offset vx : -2.3023181337396452 
scale vx : 365.7199536531911 
offset vy : -4.085005881414913 
scale vy : 362.478545105541 
offset vz : -0.24358252525521393 
scale vz : 345.5441903510959 
offset rho : -14.423473584198543 (log)
scale rho : 1.6036638474880769 (log)
offset U : 12.760782397381073 (log)
scale U : 1.5574964631262174 (log)
 

Snapshot : AGN_TUNED_nu0_L100N256_WMAP9
Simulation : Bahamas
Clusters : 200
 
offset x : 2.1594317589112503e+26 
scale x : 2.7309556071837393e+24 
offset y : 2.3561828461491217e+26 
scale y : 4.6764178702501624e+24 
offset z : 2.0055326970017528e+26 
scale z : 5.018796574433487e+24 
offset vx : 79709.27408909246 
scale vx : 16477135.181521697 
offset vy : -415762.8927257515 
scale vy : 16391100.373023773 
offset vz : -1917000.358363037 
scale vz : 16256299.673098503 
offset rho : -64.58126157218969 (log)
scale rho : 1.5763775440524699 (log)
offset U : 34.35817019335751 (log)
scale U : 1.615677783341859 (log)
 

Snapshot : AGN_TUNED_nu0_L400N1024_WMAP9
Simulation : Bahamas
Clusters : 200
 
offset x : 8.882284003622964e+26 
scale x : 6.597599189922709e+24 
offset y : 9.258229399689035e+26 
scale y : 1.1045326083792266e+25 
offset z : 8.264137721804175e+26 
scale z : 7.086545241307365e+24 
offset vx : 149980.9229691147 
scale vx : 34648452.93519127 
offset vy : -2005308.8058740222 
scale vy : 33647093.327060945 
offset vz : -6247.00762461178 
scale vz : 34596168.26832744 
offset rho : -63.54092229817029 (log)
scale rho : 1.3963785852580672 (log)
offset U : 36.1969463762324 (log)
scale U : 1.1188271476768705 (log)

**Comment by Joshuaalbert** [comment]
@MGJvanGroeningen I think the best would be to choose a simple SI unit for your scales.

What are the units for the properties above? They look different between Bahamas and Magneticum.

Let's choose some meaningful units.
For example, for cluster mass let's choose 10^14Msun.

**Comment by Joshuaalbert** [comment]
See https://github.com/Joshuaalbert/neural_deprojection/issues/32 for example of Julius' units.

**Comment by MGJvanGroeningen** [comment]
@Joshuaalbert The Bahamas data are in cgs units and the Magneticum data have 'code_length' units, but yt has a function to convert them to cgs as well. So for the current properties I'd say

- positions (x, y , z): in 10^6 pc ~(-10 to 10);
- velocities (vx, vy, vz): in 10^-4 pc/yr ~(-10 to 10);
- density: in log10( 10^-7 Msun / pc^3 ) ~(-5 to 5);
- internal energy: in log10( 10^-7 pc^2/yr^2 ) ~(-5 to 5);

I'm not sure whether there is any benefit to choosing similar units or minimizing the 10^x factors. In this case I chose the former. Also to avoid confusion: the 'log' for the rho and U scales and offsets in my initial post for this issue is the natural logarithm. So e.g. rho (in both simulations) is of the order ~10^(-28) gram/cm^3

**Comment by Joshuaalbert** [comment]
Ok, I like these scales.
This implies that your features would then range between (-10,10) for position and velocity, and (-5,5) for density and internal energy. These are good. Do you also have associated volumes/masses for the particles that you could add to the properties?

**Comment by MGJvanGroeningen** [comment]
Both the Magneticum and the Bahamas dataset have 'Mass' and 'SmoothingLength' available for the gas particles.

**Comment by Joshuaalbert** [comment]
Sure, let's include those also with appropriate units, base log. They seem to be pretty orthogonal features to the others you've got.

**Comment by MGJvanGroeningen** [comment]
Alright, the following units for the mass and smoothing length seem good

- mass: in log10( 10^8 Msun ) ~(-1 to 1);
- smoothing length: in log10( 10^5 pc ) ~(-1 to 1);

**Comment by Joshuaalbert** [comment]
Great, let's go with that!
