### ISSUE TITLE
SCD Normalisation Scales

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#32]
I'm unsure whether to use different normalization factors for each simulation, because then there will be no clear way to convert de units of 3D deprojections back to physical units. For now I've chosen some units which will give values between ~ 10 and -10 for all the values. They are as follows:

- positions (x, y , z): in parsec;
- velocities (vx, vy, vz): in 10^4 m/s;
- gravitational potential: in log10(-  J/mg or equivalently MGy);   # negative because else I can't log
- density: in log10( Msun / pc^3 );
- temperature: in log10( K );
- cell mass: in log10( Msun );
- cell volume: in log10( pc^3 ).

I still have to build the dataset and inspect the exact ranges of these values, but I suspect these conversions will give me reasonable numbers.

**Comment by JuliusHendrix** [comment]
@Joshuaalbert

**Comment by Joshuaalbert** [comment]
velocity scale is 10^4 or 10e4=10^5?

**Comment by JuliusHendrix** [comment]
> velocity scale is 10^4 or 10e4=10^5?

Fixed it
