### ISSUE TITLE
[SCD] Star Cluster real ICs

### ISSUE THREAD

**Issue by JuliusHendrix** [Joshuaalbert/neural_deprojection#5]
> estimate 4
> remaining 2020-09-09 4
> remaining 2020-10-08 1
- [x] How does collapse work?

- [x] How does radiation pressure work?

- [x] Some examples: know 5 different interesting early stage star clusters where you can see some of this.

- [x] ICs molecular cloud

**Comment by Joshuaalbert** [comment]
Taking this off the "explain to group milestone", because it's not directly needed to convey the project's concept.
