### ISSUE TITLE
[GCD] Understanding the ICM

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#8]
> estimate 14
> remaining 2020-09-11 12
> remaining 2020-09-16 7
> remaining 2020-09-18 4
> remaining 2020-09-26 2
> remaining 2020-09-27 0

- [x] 2 Dynamics/Evolution
- [x] 2 Content: cosmic ray populations, thermal (related to the fact that light comes from average random motions) populations vs. non-thermal (light comes from v x a != 0 in a magnetic field) populations. 
- [x] 3 Structures: shocks in cosmic ray population, shocks in temperature, shocks in density, radio relics, radio halos, why do X-ray shocks sometimes but not always overlap with radio shocks.
- [x] 3 Physical processes: what theories are there for driving the changes in the ICM? (Turbulence driven magnetic field amplfication, shock-only magnetic field amplification, what types of particle populations are there. What is the energy story?)
- [x] 2 Detection (in X-ray and radio): what is generating the X-ray and what is generating the radio?
- [x] 2 Principles of hierarchical assembly (talk to Martijn Oei about cosmic web formation and structure)

**Comment by Joshuaalbert** [comment]
Done with presentatoin
