### ISSUE TITLE
[GCD] Understanding galaxy cluster research limitations

### ISSUE THREAD

**Issue by MGJvanGroeningen** [Joshuaalbert/neural_deprojection#9]
> estimate 4
> remaining 2020-09-10 4
- [ ] Latest developments in galaxy cluster research: what are 5 important papers of the last 5 years in this field (talk with Reinout)
- [ ] Obstacles for new research (not necessarily yours): Talk with Reinout and also Andre Botteon

**Comment by Joshuaalbert** [comment]
Taking this down, but keep in your mind to continue
